---
info:
  title: Pydomainextractor
  description: A blazingly fast domain extraction library written in Rust
  x-cortex-git:
    github:
      alias: intsightsorg
      repository: Intsights/PyDomainExtractor
  x-cortex-tag: pydomainextractor
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: threatintel-shadow-intel
  x-cortex-groups:
  - exposure:external-ship
  - target:library
openapi: 3.0.1
servers:
- url: "/"
